modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
modId = "unpacker"
version = "1.0.0"
displayName = "Packworks"
authors = "MoneyMantra"
description = '''Adds Unpacker and Packer blocks for side-specific automation with shulker boxes, bundles, and optional Traveler's Backpack support.'''

[[dependencies.unpacker]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unpacker]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unpacker]]
modId = "travelersbackpack"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
